### ISSUE TITLE
Adding functions

### ISSUE THREAD

**Issue by bentzisla** [movsim/traffic-simulation-de#11]
Where can I add parameters like the distance between vehicles or the time it takes a car to start driving after the car in front of him did? 

Thank you

**Comment by MTGermany** [comment]
The distance between vehicles can be changed in several ways: (i) open systems, free traffic: Just increase the inflow; (ii) ring road: increase the density; (iii) open systems, congested traffic: Change the time-gap parameter of the respective model, e.g., the parameter T of the IDM and related models

By the time it takes a car to start driving after the car in front of him did you probably refer to a queue behind a traffic light or the downstream front of a traffic jam. Here, both reducing the time-gap parameter and increasing the agility parameters helps. In the IDM, reduce T (and s0)  and increase a

**Comment by MTGermany** [comment]
increase a -> increase the acceleration parameter a

**Comment by bentzisla** [comment]
First, thank you for the quick reply, I did not expect an answer that fast.
Second

**Comment by bentzisla** [comment]
First, thank you for the quick reply, I did not expect an answer that fast.

Second, about the time gap: what I want is to cause all or some of the cars (in a green light for example) to start driving simultaneously and increase the distance between them while driving. I want to examine an idea,  whether the cars starting to drive almost simultaneously (even if the cars ahead didn't distance "enough" already) instead of one after another, will improve traffic flow.
So I'm trying to figure out where and how to add this function.

Thank you

**Comment by MTGermany** [comment]
I think, nearly every car driver had that idea at some point: "Standing in the back of a traffic light queue, why it takes so long until I can start after the light turned green? Why everybody cannot start simultaneously, after all, everybody is seeing that green light?" 

One of the (pedagogical) reasons of this traffic flow simulator is that this is just not feasible. Since moving cars need more space between them than standing ones, some time is needed to build up the bigger space and that is just precisely the time it needs for the starting info to propagate backwards (by the way, with the wave velocity w of about -15 km/h). Notice that this has nothing to do with reaction times! In particular, the default IDM has a reaction time of zero. 

What you can try to do is to set the time-gap parameter to zero, the acceleration parameter a to a rather high value (a=5 m/s^2), the deceleration parameter to a rather low value (b=0.5 m/s^2). Furthermore, you need to do this for all but the leader which has normal values, e.g., a=b=1.5 m/s^2) and also have a slightly lower desired speed (e.g. v0=14 m/s while the followers have v0=15 m/s) ) In order to avoid local instabilities (cf. my textbook "traffic flow dynamics") you should also reduce the simulation update time to, say, 0.02 s  (Arne: I expect this is possible). Finally, the IIDM or ACC models work better for this scenario than the original IDM. With these settings, a queue of stopped vehicles will start nearly simultaneously (see figure for the IIDM) Notice, however, that this produces highly unstable traffic and possible crashes if you also transfer these settings to the leader.

**Comment by bentzisla** [comment]
Thank you for the detailed answer. I appreciate it very much.
Your insights about the growing space between cars helped us.

I was not able to try what you suggested about the time gap, I guess that I must use Linux for that and I'm having trouble with my Linux machine, I will take care of that and try that shortly.

Anyway, incidentally I ran into an interesting book today "The wisdom of crowds" and it had a whole chapter about this subject, and he mentioned your name along with Dr. Dirk Helbing in connection with two innovations that should make a great impact in traffic flow and in driving as it is today.
I searched over the internet and I saw that as of now there still is no such System on the market and I wonder if you happen to know why is that.
I'm interested because I and a few of my fellow students are thinking about trying to develop such a system to help resolve this problem that grows bigger every day now.  I saw that you've published more than one very detailed article about this subject. We wonder why there isn't a system like that yet. Why no one developed such a system? is it impossible or is there something else that might stop us soon?

Thank you very much.

**Comment by TehShrike** [comment]
I have a similar request – I would like to tweak the value for "how much space drivers try to leave between them and the car in front of them" as a function of their speed.

To demonstrate the hypothesis that the more space drivers are willing to leave between them and the car in front of them, the fewer traffic jams, and the higher the average traffic speed.

**Comment by TehShrike** [comment]
d'oh :-| I just realized that I could scroll down to see more options.  Stupid macOS scroll bar visuals

**Comment by MTGermany** [comment]
You should be aware, however, that this is generally only true for ring roads. In real situations with demand-driven open networks there is a balance between potential maximum throughput (increasing when lowering gaps) and stability (increasing when increasing gaps). For sufficiently responsive vehicles (IDM acceleration parameter 'a' above, say, 1.5 m/s^2), the maximum throughput prevails and, for a given demand, reducing gaps reduces jams just because the dynamic road capacity increases
  
  
   Martin
    
  
  
   
    Josh Duff ***@***.***> hat am 24.03.2021 19:48 geschrieben:
   
   
    
   
   
    
   
   
   I have a similar request – I would like to tweak the value for "how much space drivers try to leave between them and the car in front of them" as a function of their speed.
   To demonstrate the hypothesis that the more space drivers are willing to leave between them and the car in front of them, the fewer traffic jams, and the higher the average traffic speed.

**Comment by TehShrike** [comment]
Well, ring roads, and any road where the speed of traffic varies for any reason (rubbernecking, potholes, unexpected braking ahead, etc).  But yeah, there's an optimal point somewhere, and it would be cool to visually demonstrate where that is.

**Comment by MTGermany** [comment]
This is easy. Just chose your scenario, optionally throw in a few of the available obstacles such as traffic cones or caterpillars (depends on the scenario), optionally impose some speed limits to reflect potholes and the like and simulate. Then, change the time gap T, the driver's agility a, or other parameters and restart the simulation using the green arrow button to the right of the stop/go button. This restarts the simulation without changing your setup of the obstacles and speed limits. Then just try optimize the traffic flow by varying the T and 'a' parameter
