### ISSUE TITLE
Ideal ACC + MOBIL parameters for real measurement vehicles.

### ISSUE THREAD

**Issue by tinbeyondcad** [movsim/traffic-simulation-de#12]
Hi,

We are adapting your work to develop a simulation on a game engine. We would like to know the ideal parameters for ACC + MOBIL models to use on vehicles with real-life measurement (vehicle's length).

Thanks!

**Comment by MTGermany** [comment]
Hello,
  
  
   
  
  
   the model parameters depend, of course, on the driving style and environment. 
  
  
   
  
  
   Interestingly, the environment (city, rural, freeway) can be covered by the desired speed v0 alone with obvious values. In my textbook, the other ACC model parameters are set as 
  
  
   1.2 T = savety time gap (s)
   2. s0 = min. bumper-to-bumper distance (m)
   4 delta = Acceleration exponent
   1.5 a = acceleration (m/s^2)
   1.5 b = comfortable braking deceleration (m/s^2)
   
  
  
   0.98  = coolness parameter (0=IDM, 1=extra cool)
  
  
   This corresponds to a rather relaxed driving style (notice that  the recommended gap rule (in meters) in Europe is half the speedometer reading in km/h corresponding to T=1.8 s but hardly anybody respect this nor would it lead to efficient traffic flow). If you want a more responsive  driver, increase the acceleration parameter 'a' to values of about 3 m/s^2; if you want to make him or her more aggressive, reduce T and/or increase b. The minimum gap is just relevant for a complete standstill (with obvioius meaning) and delta=4 can be used at any situation
   
   Generally, the lane changing model MOBIL inherits the traits of the driving style from the longitudinal model (here, the ACC model) since it is formulated in terms of the accelerations. Its own parameters may have following values
   politeness factor p: p=0.1-0.2 for a normal, p=0 for a selfish, and p=1 for a rather altruistic driver  
   lane changing threshold Delta b=0.2 m/s^2: About ten percent of the acceleration paramter 'a'
   lane bias b_bias =0.3 m/s^2if there is a lane usage rule (e.g., a bias in favour of the right lane if there is a "keep right" rule. Notice that b_bias must be > Delta b
   Additional recommendations for the lane changes: Since the lane changing model is discrete which does not look well in the simulator, move the cars slowly to the new lane in about 3-4 seconds, starting at the time of the MOBIL decision. Furthermore, prevent unrealistic fast zapping between two lines  by prohibiting lane changes of all the neighboring cars for about 3 seconds once a lane change is realized. Also prevent the subject driver from further changes for about 5 seconds. 
   
   Best,
   
   Martin
    ----------------------------------------------------------Dr. Martin TreiberInstitute for Transport & Economics, TU DresdenChair of Traffic Modelling, Econometrics, and StatisticsFalkenbrunnen, Room 123 (two floors up from the entrance!)Würzburger Str. 35, D-01062 Dresdenmartin@mtreiber.dewww.mtreiber.dephone/fax: +49 (351) 463 36794 / 36809---------------------------------------------------------
  
  
   
    tinbeyondcad <notifications@github.com> hat am 24.09.2020 22:55 geschrieben:
   
   
    
   
   
    
   
   
   Hi,
   We are adapting your work to develop a simulation on a game engine. We would like to know the ideal parameters for ACC + MOBIL models to use on vehicles with real-life measurement (vehicle's length).
   Thanks!

**Comment by tinbeyondcad** [comment]
Hi Dr. Martin,

I'm implementing a simple conflict zone decision making but not sure how to approach this. In the pictures, the vehicles on the offramp road should yield for all vehicles on the main road. I have them stopping at the yield point (a dummy obstacle) but wasn't sure how to calculate the parameters for those vehicles to proceed safely. Any insight is appreciated!
![tempsnip](https://user-images.githubusercontent.com/69932349/101132913-a8f9d080-35bc-11eb-97a4-6ac866f5d73a.png)

**Comment by MTGermany** [comment]
Hello,
basically you can use the MOBIL lane-changing heuristic for this case as well. In the simplest case of a stopping line directly before entering the priority road, it is just the safety criterion (the incentive criterion is always fulfilled since you do not want to wait forever ;-) ). So, logically, you can make the merging road go in parallel to the priority road. Enter whenever you will not collide with the leader on the target lane (in the figure, the leftmost lane of the priority road) and simultaneously the new follower on the priority lane needs not to brake stronger than with the safe deceleration b_safe=b (with b the IDM model parameter). Assume that the new follower drives according to the ACC or IDM model (try it out, the merging condition is less strict for the ACC model since it also considers the leader's (i.e., your)  acceleration which you can assume to be equal to the IDM parameter a.

Things become a bit more complicated if no stopping is required. Then, you need to define a decision point, maybe 10-50 m before you reach the merging point (the last point where you can safely stop without obstructing the mainroad vehicles). The position depends  on the visibility, the design speeds of the road network, and the curvature of the merging road. Then proceed as follows
1. Approach and cross the imaginary decision point as if you would have to stop directly at the *merging* point
2. At the decision point, anticipate if you can enter the priority road at unchanged speed, i.e., if the anticipated lane changing safety criterion will be fulfilled at merging time. If yes, proceed according to this decision (and accelerate after the merge). Otherwise approach the merging point as if you would have to stop at it, i.e., just continue your braking maneuver. Repeat calculating the safety criterion until it is fulfilled (which may be before or after the stop)
