### ISSUE TITLE
How much if at all does timewarp affect the outcome of the simulation?

### ISSUE THREAD

**Issue by UrKr** [movsim/traffic-simulation-de#13]
I apologise if this is not the place, but I don't know where else to ask. 

As in the title:
How much does changing the timewarp affect the outcome of the simulation. Since the _dt_ is different.

**Comment by UrKr** [comment]
I saw that the dt is static.

**Comment by MTGermany** [comment]
The time step dt is not constant. In fact, it is set by the command 

var dt=timewarp/fps;

as a function of the user-set timewarp (time-lapse factor) and the frame rate fps which is set as constant (in most simulations, fps=30). However, for timewarp  values below 10 times, the effect is minimal because, in this case, the numerical update time step dt<=0.33 s where the used integration scheme (ballistic scheme, see info at traffic-simulation.de) has only marginal discretisation errors. However, when increasing the timewarp to the max, there are small but significant differences which, however, are not recognized in all the dynamics. More details on numerical update methods and their precision for car-following simulations can be found in my paper

Martin Treiber and Venkatesan Kanagaraj (2015)
Comparing Numerical Integration Schemes for Time-Continuous Car-Following Models
Physica A: Statistical Mechanics and its Applications 419C, 183-195
DOI 10.1016/j.physa.2014.09.061
[arxiv e-print 1403.4881]
