### ISSUE TITLE
userCanDistortRoads

### ISSUE THREAD

**Issue by Resccc** [movsim/traffic-simulation-de#17]
If I set userCanDistortRoads to true, I can drag the road freely, but it is reset as soon as I refresh. Is there anything I can do to save the changes I made to the road on the page

**Comment by MTGermany** [comment]
The dragging of roads interfered with the new design for creating and connecting networks in a more general way and always lead to inconsistencies and conflicts, so I deactivated it globally and will not pursue it further.  I can, however, make available a legacy version where I  can treat your issue. Stay tuned

**Comment by MTGermany** [comment]
Ohh, I forgot to close this issue. Since the new functionality of intersections and general functionality to built up networks is not compatible with arbitrariliy changing the geometry by user interactions, I published a legacy version in the subdirectory traffic-simulation-de_legacyDistortRoads/ which is the latest version where userCanDistortRoads can be set to true. See also the online simulation at  https://mtreiber.de/trafficSimulationDe_legacyDistortRoads/index.html
