### ISSUE TITLE
Findleaderatlane

### ISSUE THREAD

**Issue by mattinjersey** [movsim/traffic-simulation-de#20]
For the function findleaderatlane, it seems to step through vehicles and choose the last. How do we know this is the nearest? Seems like it should compute the distance and then check if the distance is minimum?

**Comment by MTGermany** [comment]
After updating the positions all vehicles are sorted according to longitudinal position (road.sortVehicles()) which is called as one of the last actions of road.updateSpeedPositions(). Since updating positions is the only operation where the order can get mixed up (merging/diverging, inflow/outflow and the road connectors have their own explicit index handling conserving the order) we have always longitudinally ordered vehicles. So just finding the highest vehicle index on a given lane with longitudinal position u greater than the argument position is enough to find the right leader

**Comment by MTGermany** [comment]
I think this is settled now. If you think otherwise, you may open another issue
