### ISSUE TITLE
Range of velocities

### ISSUE THREAD

**Issue by mattinjersey** [movsim/traffic-simulation-de#21]
Are the vehicles too "perfect"? They all accelerate to the same speed and maintain the speed. Should there be more random behavior?

**Comment by MTGermany** [comment]
In fact, there is some random behaviour but only in form of a random acceleration term, see the local variable this.noiseAcc in the car-following models of models.js. Furthermore, there is of course a difference between cars and trucks. 
Nevertheless, you are right, all cars behave, on average, the same because they have the same desired speed etc. Furthermore, the random acceleration also interferes with the lane-changing module in a less than optimal way. Both are valid objections and I will deal with them in the near future

**Comment by MTGermany** [comment]
Variable driving characteristics are now implemented. At construction time of the vehicles, a random "agility variable" is set influencing desire speed and desired acceleration in a persistent way throughout all situations and driving conditions or user-controlled global behaviour changes. All stochasticity (whether persistent to the driver or the random acceleration part) are removed for all purposes except longitudinal acceleration (lane changing, merging, crossing etc)
