### ISSUE TITLE
Weird circulation

### ISSUE THREAD

**Issue by jalovisko** [movsim/traffic-simulation-de#3]
Setting up the parameters as in the image below
![IMAGE 2019-04-16 11:42:42](https://user-images.githubusercontent.com/22379984/56223953-bf949200-603c-11e9-9d4a-f09fff81cb86.jpg)

results in weird circulations of traffic.
<img width="715" alt="image" src="https://user-images.githubusercontent.com/22379984/56224043-ec48a980-603c-11e9-9bd5-f17b2ff185f5.png">

**Comment by MTGermany** [comment]
Thanks for pointing this out. In fact, I have the problem cornered to just the sliders for the acceleration a and time gap T. With all other sliders at default, I reproduced the observation that the roundabout scenario will lead to these strange effects (after some time) when setting the a and T sliders to their respective minimum values. A quick fix would be to allow only a>=0.5 m/s^2 but I will try find out what is the true reason for this bug.

**Comment by MTGermany** [comment]
Fixed. Reason: For extreme settings (smallest a AND T, high timewarp implying large numerical timesteps, vehicles may crash and, since virtual obstacle has length zero, the order of vehicles is swapped. Thus, without correction, vehicles just drive past the obstacle on a forbidden trajectory. I just moved the overrunning vehicle externally back and also re-swapped the properties (outomatically done at road.update in orer to have correct positional ordering)
