### ISSUE TITLE
Library / Wrapper for offline use?

### ISSUE THREAD

**Issue by solarjoe** [movsim/traffic-simulation-de#4]
We came across your software searching for ways to investigate the propagation of traffic waves.
The model needs to run offline, coupled to Python to interface AI toolkits.
Of course we would like to avoid a complete rewrite in Python :)

Maybe it is possible to run your code on the sever-side using NodeJS and interface somehow to inject and export data into the model. 

Do you know what could be a good way to do this? Is there maybe a C library available that we could wrap? I found some rather simple implementations of IDM in Python that seem to be derived from your JS code, but they won't do.

**Comment by MTGermany** [comment]
I never worked much with Python. However, there seems to be a github page
https://github.com/davisp/python-spidermonkey
whose authors claim that their tool can "execute arbitrary JavaScript code from Python." I wonder if this is not exactly what you want to do.

**Comment by solarjoe** [comment]
Ok, I will look into it.

Yet another question, on the model, hope you don't mind me asking it here.

On the docs to the model, e.g. [here](http://mtreiber.de/trafficSimulationDe_html5_2016_06_29/IDM.html), you state 

> For our purposes, it turned out that following ballistic scheme is most efficient in terms of computation load for a given precision.

But Wikipedia states on [IDM](https://en.wikipedia.org/wiki/Intelligent_driver_model) that the two ordinary differential equations are solved using Runge–Kutta methods for computational accuracy to show effects like traffic wave propagation.

Does this mean that the JavaScript simulation is rather coarse and not correct to the last detail?

**Comment by MTGermany** [comment]
Interestingly, that is only half the truth. Of course, as in other ODE integration tasks, a higher-order numerical integration scheme gives results closer to the exact solution than a lower-order one. However, there are two caveats:
(1) This is only true when comparing two methods with identical update time steps dt. However, an integration method of order k needs k evaluations of the right-hand sides of the ODE system per time step, so the numerical complexity C (number of operations per vehicle-second of simulation) scales with k/dt, not just with 1/dt. Since the numerical complexity is directly related to the computation time, this is what counts, and one should compare two routines keeping C=const, i.e., the update time of a routine of k-th order needs to be k times that of the Euler or the ballistic schemes which are both of first order. 

(2) There is some fine print in the theory of numerical mathematics: The approximate solution x_num(t) to an ODE with right-hand side f() [both x and f(.) can be vectors)] with a scheme of order k is only then of global consistency order k if f(.) can be differentiated at least k times (and is Lipschitz-continuous). This is perfectly valid for the IDM whose right-hand side f(.) is smooth (infinitely often differentiable) with the exception of few instances where the max-condition of s* applies. However, when considering lane changes (e.g., combining IDM with MOBIL), locally varying speed limits, and other aspects of real traffic, f() is no longer smooth. It may not even be differentiable, and can even be disontinuous. Then, the global consistency order is limited by f(.), not by the order of the integration scheme and higher-order schemes are useless, or even worsen the approximation even when keeping dt=constant (!)

(3) A higher global consistency order is not necessarily better since there is a scheme-dependent prefactor in the discretisation error which can more than compensate for a lower order for practical update time steps of the order of 0.1 to 0.2 s. For example, while the ballistic and Euler schemes are both of first order, the prefactor of the ballistic schemes is more than an order of magnitude lower than that of the Euler scheme, so the former is always to be preferred to the latter 

In Ref [1], we discuss all three points and show

(i) for the numerical integration of single-lane IDM, the Trapezoidal scheme (=RK2) is best in terms of accuracy per numerical complexity, at least for practical update time steps dt=0.1 s - 0.2 s

(ii) Whenever there are some external perturbations (lane changes, speed limits,...), the ballistic scheme (which is not an element of the set of generic RK<k> models) is best in terms of accuracy/numerical complexity
 
[1] Martin Treiber and Venkatesan Kanagaraj (2015)
Comparing Numerical Integration Schemes for Time-Continuous
Car-Following Models. Physica A: Statistical Mechanics and its Applications 419C, 183-195
DOI 10.1016/j.physa.2014.09.061
[arxiv e-print 1403.4881]

**Comment by MTGermany** [comment]
Regarding the usecase of this simulation, traffic-simulation.de: The simulated scenarios contain many discontinuous external factors (lane changes, traffic lights, speed-limit zones and, last but not least, users clicking on some of the vehicles. Therefore,  the aplied ballistic scheme is, indeed, the best for this application

**Comment by solarjoe** [comment]
Ok, got it. Thank you very much for the elaborate answer and the hint on the paper!

The spidermonkey link you send earlier is not an ideal solution. We will probably use NodeJS to run the code. There we are able to export the traffic data to files or alternatively stream them using WebSocket.

**Comment by ran-ka** [comment]
Hi, I managed to extract the data by modifying the JS code and sending the data to a REST endpoint which runs a very simple Python server locally. If you are still interested I can send you the details on how to do it. (Or potentially raise a pull request)

**Comment by MTGermany** [comment]
Thanks for your offer. I am very interested in knowing how to do it

**Comment by ran-ka** [comment]
Sure!
what I did was basically modifying road.prototype.writeVehicles in road.js so that instead of writing the data to console.log it just sent it to a local endpoint like this: (log is a string which holds a CSV line for each vehicle status)

  var url = 'http://localhost:8000';
  var xhr = new XMLHttpRequest();
  xhr.open('POST', url, false);
  xhr.send(log);

Separately, I wrote this basic HTTP server in python which I run locally:

from http.server import HTTPServer, BaseHTTPRequestHandler
from io import BytesIO


class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):

    def log_message(self, format, *args):
        return

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length).decode("utf-8")
        reader = csv.reader(body.split('\n'), delimiter=',')
        for row in reader:
            print(','.join(row))
        self.send_response(200)
        self.send_header("Content-type", "text/plain")
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        response = BytesIO()
        response.write(b'This is POST request. ')
        response.write(b'Received: ')
        self.wfile.write(response.getvalue())

httpd = HTTPServer(('localhost', 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()

I hope this makes sense... I just used it to export the data so that I can run some computation in python

**Comment by zlg9folira** [comment]
@ran-ka what kind of data your wrapper saves in CSV? 
I am actually looking for a way to run the simulation and save the data (for all vehicles) as in the form below:

[time][vehicle ID][x,y position][speed][accel][heading]

Can anyone help me on saving data, I am going to convert such data to use it within NS-3 simulator.

**Comment by MTGermany** [comment]
This is now implemented. CSV in the format mentioned above. In the simulations, a new blue download button is there at the bottom. Clicking it once starts the storage for the download, clicking it again ("finish") actually downloads for the download period  all the vehicle dynamic variables of all the roads of the network in files road<n>_time<ss>.txt where <n> is the n'th road and <ss> is the finishing time in seconds. The files are saved in the default folder (usually Downloads/) The vehicles are saved every second but the time interval can be changed by the variable var dt_export=1; in control_gui.js
